version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-net
    user: root  
    command: >
        bash -c "apt-get update && apt-get install -y git && /sbin/tini -- /usr/local/bin/jenkins.sh"

  dind:
    image: docker:24-dind
    container_name: docker-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - dind-certs:/certs/client
    networks:
      - jenkins-net

volumes:
  jenkins_home:
  dind-certs:

networks:
  jenkins-net:
    driver: bridge
