pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'my-app-image'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t $DOCKER_IMAGE .'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    sh 'docker run -d --name temp_container $DOCKER_IMAGE'
                }
            }
        }

        stage('Clean Up') {
            steps {
                script {
                    sh '''
                        docker stop temp_container || true
                        docker rm temp_container || true
                    '''
                }
            }
        }
    }

    post {
        always {
            sh 'docker rmi $DOCKER_IMAGE || true'
        }
    }
}
